---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2020-05-26 - 07:57:17 +0000"
    app: "micronaut-example"
  labels:
    app.kubernetes.io/name: "micronaut-example"
    app.kubernetes.io/version: "1.0.0"
  name: "micronaut-example"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2020-05-26 - 07:57:17 +0000"
    app: "micronaut-example"
  labels:
    app.kubernetes.io/name: "micronaut-example"
    app.kubernetes.io/version: "1.0.0"
  name: "micronaut-example"
spec:
  ports:
  - name: "http"
    port: 8090
    targetPort: 8090
  selector:
    app.kubernetes.io/name: "micronaut-example"
    app.kubernetes.io/version: "1.0.0"
  type: "ClusterIP"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2020-05-26 - 07:57:17 +0000"
    app: "micronaut-example"
  labels:
    app.kubernetes.io/name: "micronaut-example"
    app.kubernetes.io/version: "1.0.0"
  name: "micronaut-example:view"
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: "view"
subjects:
- kind: "ServiceAccount"
  name: "micronaut-example"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2020-05-26 - 07:57:17 +0000"
    app: "micronaut-example"
  labels:
    app.kubernetes.io/name: "micronaut-example"
    app.kubernetes.io/version: "1.0.0"
  name: "micronaut-example"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "micronaut-example"
      app.kubernetes.io/version: "1.0.0"
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: "2020-05-26 - 07:57:17 +0000"
        app: "micronaut-example"
      labels:
        app.kubernetes.io/name: "micronaut-example"
        app.kubernetes.io/version: "1.0.0"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "elvaliev/micronaut-quickstart:latest"
        imagePullPolicy: "Always"
        name: "micronaut-example"
        ports:
        - containerPort: 8090
          name: "http"
          protocol: "TCP"
      serviceAccount: "micronaut-example"
