#!/usr/bin/env bash
application=$1
image=$2
templatePath=$3
port=$4

echo "Starting creating $application from docker registry $image by template from $templatePath"
kubectl create deployment "$application" --image="$image"
kubectl create -f "$templatePath" --record --save-config
echo "Expose $application on port=$port"
kubectl expose deployment "$application" --type=LoadBalancer --port="$port"
