# Setup
title:               QuickStart
tagline:             'Hello-World Deployment by Gradle tasks'
description:         'Deploy your application by using Gradle tasks'
url:                 http://elina.valieva.quickstart.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Elina Valieva
  url:               https://github.com/ElinaValieva
  email:             Elina.Valieva@t-systems.com

# Gems
plugins:
  - jekyll-feed


# Custom vars
version:             1.0.3
google_analytics_id: #UA-XXXX-Y
