# Setup
title:               QuickStart
tagline:             'Deployment for Hello-World App by Gradle tasks'
description:         '<p/><p/>'
url:                 https://elinavalieva.github.io/micronaut-quickstarts
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Elina Valieva
  url:               https://github.com/ElinaValieva
  email:             Elina.Valieva@t-systems.com

# Gems
plugins:
  - jekyll-feed

# Custom vars
github:
  repo:              https://github.com/ElinaValieva/micronaut-quickstarts
