# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build for k8s-plugin
        run: |
          cd k8s-plugin
          chmod +x gradlew
          ./gradlew build
          ./gradlew install
          cd ..
      - name: Test with Gradle
        run: ./gradlew test
      - name: Jib
        if: github.ref == 'refs/heads/master'
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: elvaliev/micronaut-quickstart
        run: ./gradlew jib --image=$DOCKERHUB_REPOSITORY -PDOCKERHUB_USERNAME=$DOCKERHUB_USERNAME -PDOCKERHUB_PASSWORD=$DOCKERHUB_PASSWORD